### ISSUE TITLE
make -f makefile.unix    ubuntu 16.04

### ISSUE THREAD

**Issue by goodthebest** [Bitspacedev/BitSpace#1]
Hi @Bitspacedev 
I'm trying to compile on ubuntu 16.04, however I keep geting error. What is the correct way to compile it on OS Ubuntu 16.04?

`cd BitSpace/src`
`make -f makefile.unix`

>/root/BitSpace/src/txdb-leveldb.h:114: undefined reference to `leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)'
/root/BitSpace/src/txdb-leveldb.h:119: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
obj/txdb-leveldb.o: In function `bool CTxDB::Write<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, uint256>, CTxIndex>(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, uint256> const&, CTxIndex const&)':
/root/BitSpace/src/txdb-leveldb.h:114: undefined reference to `leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)'
/root/BitSpace/src/txdb-leveldb.h:119: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
obj/txdb-leveldb.o:(.rodata._ZTI13CBatchScanner[_ZTI13CBatchScanner]+0x10): undefined reference to `typeinfo for leveldb::WriteBatch::Handler'
collect2: error: ld returned 1 exit status
makefile.unix:206: recipe for target 'bitspaced' failed
make: *** [bitspaced] Error 1

**Comment by Bitspacedev** [comment]
You have to use Ubuntu 14.04.

- sudo apt-get update

- sudo apt-get upgrade

- sudo apt-get install build-essential libssl-dev libdb-dev libdb++-dev
libboost-all-dev git libssl1.0.0-dbg

- sudo apt-get install libdb-dev libdb++-dev libboost-all-dev
libminiupnpc-dev libminiupnpc-dev libevent-dev libcrypto++-dev libgmp3-dev



2018-03-10 3:07 GMT+01:00 goodthebest <notifications@github.com>:

**Comment by Bitspacedev** [comment]
Guide
https://bit-space.io/bsx-coin-deamon/
